# Generated by Django 3.2.12 on 2022-05-19 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220517_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('picked', models.BooleanField(default=False)),
                ('items', models.CharField(max_length=1000)),
                ('delivered', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
                ('has_tracking_id', models.BooleanField(default=False)),
                ('Tracking_id', models.CharField(default='will update soon', max_length=200)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
