# Generated by Django 3.2.12 on 2022-05-19 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Tracking_id',
            new_name='tracking_id',
        ),
        migrations.AddField(
            model_name='newuser',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='telangana'),
            preserve_default=False,
        ),
    ]
