# Generated by Django 3.2.12 on 2022-05-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220519_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='newuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(default='123', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
