# Generated by Django 3.2.12 on 2022-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220520_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
