# Generated by Django 4.0.5 on 2022-06-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_orders_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='weight',
        ),
    ]
